### ISSUE TITLE
Can I run this model in real time?

### ISSUE THREAD

**Issue by physxP** [ZhengyiLuo/MEVA#5]
In the code I see that you extract all the frames of the video and then ran the tracker and inference on the code. My question is that is there a possibility of running this in real time on an a live video stream if I start modifying the code or does your model requires complete video? Also are there any FPS benchmarks for this model on GPUs? Thanks

**Comment by ZhengyiLuo** [comment]
Hi! Thank you for checking out my code! 

MEVA does not need a full video to run, but it does process frames in batches (90 frames at a time). Processing it in batches allow it to extra much more temporally smooth sequences. By design it would be hard to run MEVA in a real time data stream. The code can roughly run in 10FPS amortized over the whole 90 frames.

**Comment by physxP** [comment]
Thank you so much for the quick and helpful response. Hope that you keep doing such an amazing research.
